kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql
  labels:
    type: local-mysql
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/mysql"