apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  namespace: app
  labels:
    app: wordpress-mysql
spec:
  serviceName: wordpress-mysql
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom:
          - secretRef:
              name: wordpress-mysql-env
          - configMapRef:
              name: wordpress-mysql-env
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: wordpress-mysql-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: wordpress-mysql-pvc
      spec:
        storageClassName: manual
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        selector:
          matchLabels:
            type: local-mysql