apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: app
  labels:
    app: wordpress-mysql
spec:
  selector:
    app: wordpress-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  clusterIP: None
