apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: app
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort