---
- name: Install nfs server
  apt:
    name: nfs-kernel-server 
    state: present
    update_cache: yes

- name: Create dir and set permissions
  command: "{{ item }}"
  with_items:
    - mkdir -p /nfs-share/wordpress
    - chown nobody:nogroup /nfs-share/
    - chmod 777 /nfs-share/

- name: Configure exports
  shell: "{{ item }}"
  with_items:
    - echo "/nfs-share 	*(rw,sync,no_root_squash)" >> /etc/exports
    - exportfs -rv

- name: Restart NFS service
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted

- name: Get nfs server ip
  shell: "ip a | grep inet | awk 'FNR == 3 {print $2}' | cut -d '/' -f1"
  register: nfsIP

- name: Replace nfs server ip in wordpress app manifest
  replace:
    path: "{{ playbook_dir }}/../../app/wordpress/pv.yaml"
    regexp: '(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    replace: "{{ nfsIP.stdout }}"
  delegate_to: localhost
