---
- name: Install nfs server
  apt:
    name: nfs-kernel-server 
    state: present
    update_cache: yes

- name: Setup NFS
  shell: "{{ item }}"
  with_items:
    - mkdir -p /nfs-share/wordpress
    - echo -e "/nfs-share 	*(rw,sync,no_root_squash)" >> /etc/exports
    - exportfs -rv
    - chown nobody:nogroup /nfs-share/
    - chmod 777 /nfs-share/
    - systemctl restart nfs-kernel-server

- name: Get nfs server ip
  shell: "ip a | grep inet | awk 'FNR == 3 {print $2}' | cut -d '/' -f1"
  register: nfsIP

- name: Replace nfs ip in manifest
  replace:
    path: "{{ playbook_dir }}/../../app/wordpress/pv.yaml"
    regexp: '(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    replace: "{{ nfsIP.stdout }}"
  delegate_to: localhost
