apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.96.96.96
    path: "/"
  mountOptions:
    - nfsvers=4.1
