apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
  namespace: nfs
spec:
  serviceName: nfs-server
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: gists/nfs-server:2.5.4
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - SETPCAP
          env:
            - name: NFS_OPTION
              value: "fsid=0,rw,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide"
          volumeMounts:
            - mountPath: /nfs-share
              name: nfs-server-pvc
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 200m
  volumeClaimTemplates:
    - metadata:
        name: nfs-server-pvc
      spec:
        storageClassName: manual
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        selector:
          matchLabels:
            type: local-nfs
